//
//  AppearanceStore.swift
//  Mochi
//
//  Persists optional custom pet appearances chosen or generated by the user.
//

import AppKit

enum AppearanceStore {
    private static var homeDir: URL {
        if let override = ProcessInfo.processInfo.environment["MOCHI_HOME"], !override.isEmpty {
            return URL(fileURLWithPath: override, isDirectory: true)
        }
        return FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".mochi")
    }

    private static var legacyImageURL: URL {
        homeDir.appendingPathComponent("appearance.png")
    }

    static var appearancesDir: URL {
        homeDir.appendingPathComponent("appearances", isDirectory: true)
    }

    static var walkFramesDir: URL {
        appearancesDir.appendingPathComponent("walk", isDirectory: true)
    }

    static func imageURL(for role: AppearanceRole) -> URL {
        appearancesDir.appendingPathComponent("\(role.rawValue).png")
    }

    static func loadAll() -> [AppearanceRole: NSImage] {
        var result: [AppearanceRole: NSImage] = [:]
        for role in AppearanceRole.allCases {
            if let image = NSImage(contentsOf: imageURL(for: role)) {
                result[role] = image
            }
        }

        // Migrate the earlier single-image customization into the companion slot.
        if result.isEmpty, let image = NSImage(contentsOf: legacyImageURL) {
            result[.companion] = image
        }
        return result
    }

    static func loadWalkFrames() -> [NSImage] {
        guard let urls = try? FileManager.default.contentsOfDirectory(at: walkFramesDir,
                                                                      includingPropertiesForKeys: nil)
        else { return [] }
        return urls
            .filter { $0.pathExtension.lowercased() == "png" }
            .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }
            .compactMap { NSImage(contentsOf: $0) }
    }

    static func saveMany(from sourceURLs: [URL]) throws -> [AppearanceRole: NSImage] {
        let assignments = assign(sourceURLs)
        guard !assignments.isEmpty else { throw AppearanceError.unreadableImage }

        try FileManager.default.createDirectory(at: appearancesDir, withIntermediateDirectories: true)
        var saved: [AppearanceRole: NSImage] = [:]
        for (role, sourceURL) in assignments {
            guard let image = NSImage(contentsOf: sourceURL) else { continue }
            guard let pngData = image.pngData(maxPixelSize: 1024) else { continue }
            try pngData.write(to: imageURL(for: role), options: .atomic)
            saved[role] = image
        }

        if saved.isEmpty { throw AppearanceError.unwritableImage }
        return saved
    }

    /// Install a whole appearance-pack folder at once: the state images in its
    /// root (assigned to roles by filename) plus any `walk/` frames. Replaces
    /// the current pack so it acts as a clean "switch to this pack".
    static func importPack(from folder: URL) throws {
        let fm = FileManager.default
        let pngs: (URL) -> [URL] = { dir in
            ((try? fm.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil)) ?? [])
                .filter { $0.pathExtension.lowercased() == "png" }
        }
        let assignments = assign(pngs(folder))
        let walkFrames = pngs(folder.appendingPathComponent("walk", isDirectory: true))
            .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }
        guard !assignments.isEmpty || !walkFrames.isEmpty else { throw AppearanceError.unreadableImage }

        clear()
        try fm.createDirectory(at: appearancesDir, withIntermediateDirectories: true)
        for (role, src) in assignments {
            try? fm.copyItem(at: src, to: imageURL(for: role))
        }
        if !walkFrames.isEmpty {
            try fm.createDirectory(at: walkFramesDir, withIntermediateDirectories: true)
            for (i, src) in walkFrames.enumerated() {
                try? fm.copyItem(at: src, to: walkFramesDir.appendingPathComponent(String(format: "frame_%02d.png", i)))
            }
        }
    }

    static func clear() {
        try? FileManager.default.removeItem(at: appearancesDir)
        try? FileManager.default.removeItem(at: legacyImageURL)
    }

    private static func assign(_ urls: [URL]) -> [AppearanceRole: URL] {
        let sorted = urls.sorted {
            $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending
        }
        var assigned: [AppearanceRole: URL] = [:]
        var unassigned: [URL] = []

        for url in sorted {
            let name = url.deletingPathExtension().lastPathComponent
            if let role = roleForFilename(name), assigned[role] == nil {
                assigned[role] = url
            } else {
                unassigned.append(url)
            }
        }

        for role in AppearanceRole.allCases where assigned[role] == nil {
            guard !unassigned.isEmpty else { break }
            assigned[role] = unassigned.removeFirst()
        }
        return assigned
    }

    private static func roleForFilename(_ filename: String) -> AppearanceRole? {
        let name = filename.lowercased()
        if containsAny(name, ["work", "working", "busy", "think", "coding", "工作", "干活", "忙", "思考"]) {
            return .work
        }
        if containsAny(name, ["rest", "sleep", "nap", "休息", "睡", "困"]) {
            return .rest
        }
        if containsAny(name, ["slack", "lazy", "fish", "break", "摸鱼", "偷懒", "发呆"]) {
            return .slack
        }
        if containsAny(name, ["drag", "hold", "lift", "stand", "拖拽", "拖动", "拎", "站立", "站起来"]) {
            return .drag
        }
        if containsAny(name, ["companion", "idle", "default", "normal", "陪伴", "日常", "默认"]) {
            return .companion
        }
        return nil
    }

    private static func containsAny(_ string: String, _ needles: [String]) -> Bool {
        needles.contains { string.contains($0) }
    }
}

enum AppearanceError: Error {
    case unreadableImage
    case unwritableImage
}

private extension NSImage {
    func pngData(maxPixelSize: CGFloat) -> Data? {
        let sourceSize = size
        guard sourceSize.width > 0, sourceSize.height > 0 else { return nil }
        let scale = min(1, maxPixelSize / max(sourceSize.width, sourceSize.height))
        let targetSize = NSSize(width: sourceSize.width * scale, height: sourceSize.height * scale)
        let targetRect = NSRect(origin: .zero, size: targetSize)

        guard let bitmap = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: max(1, Int(targetSize.width.rounded())),
            pixelsHigh: max(1, Int(targetSize.height.rounded())),
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ) else { return nil }

        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: bitmap)
        NSColor.clear.setFill()
        targetRect.fill()
        draw(in: targetRect, from: .zero, operation: .sourceOver, fraction: 1.0)
        NSGraphicsContext.restoreGraphicsState()

        return bitmap.representation(using: .png, properties: [:])
    }
}
